### ISSUE TITLE
gpg_encrypt tar 1st

### ISSUE THREAD

**Issue by WnndGws** [WnndGws/dotfiles#4]
Want to tar 1st then gpg, thus allowing gpg_encrypt of folders too

**Comment by WnndGws** [comment]
Done with 7z

**Comment by ammgws** [comment]
Could you please link me to the specific commit?

**Comment by WnndGws** [comment]
https://github.com/WnndGws/dotfiles/commit/8b774ab823c9c58358940ef79aaad3cedda475af
